version: '3.8'

services:
  db:
    image: postgres:15.1-alpine
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - .env
    restart: always
    ports:
      - 5432:5432
    expose:
      - 5432
    networks:
      - web_network

  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    entrypoint: >
      sh -c "
        alembic upgrade head &&
        uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
      "
    restart: always
    volumes:
      - .:/app
    networks:
      - web_network
    ports:
      - 8000:8000
    expose:
      - 8000
    depends_on:
      - db


networks:
  web_network:
    name: web_network