version: '3.8'

services:
  db:
    image: postgres:14
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - 5432:5432
    expose:
      - 5432
    networks:
      - web_network

  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - web_network
    ports:
      - 8000:8000
    depends_on:
      - db


networks:
  web_network:
    name: web_network