"""Discount add

Revision ID: f175ad7487a4
Revises: fe4f9ee29f61
Create Date: 2023-08-17 13:52:42.574308

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'f175ad7487a4'
down_revision = 'fe4f9ee29f61'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dish', sa.Column('discount', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dish', 'discount')
    # ### end Alembic commands ###
